// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-tTUf3szHSI8AvhJtAVfR0Eoo3GW7JY8',
    appId: '1:532302998895:android:f196220c968daa8a688c9a',
    messagingSenderId: '532302998895',
    projectId: 'sarana-bahagia-berkah',
    storageBucket: 'sarana-bahagia-berkah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxkHf6rywNEuIqEPXgD-YXQWSGXmmaU2k',
    appId: '1:532302998895:ios:b4383a80d4a2fc1d688c9a',
    messagingSenderId: '532302998895',
    projectId: 'sarana-bahagia-berkah',
    storageBucket: 'sarana-bahagia-berkah.firebasestorage.app',
    androidClientId: '532302998895-41m80s1335llc2p1inhjq7tb2j37223e.apps.googleusercontent.com',
    iosClientId: '532302998895-1f8lrg4v905gkpdb8g6kolf692jo9ism.apps.googleusercontent.com',
    iosBundleId: 'com.saranabahagiaberkah.app',
  );

}